spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 589404963040-01tf2olk54i1l40r6puotfggh12rcoib.apps.googleusercontent.com
            clientSecret: InZReau1ae_b30ooLfGFuE1I
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/assessment?serverTimezone=UTC
    username: root
    password: 4321
logging:
  level:
    root: info
  file:
    name: assessment.log